spring.datasource.url=jdbc:postgresql://localhost:5432/smartsplit_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


jwt.secret=your-super-secret-key-minimum-32-characters-long-smartsplit2026

spring.mail.username=chavanprathamesh813@gmail.com
spring.mail.password=kteuckcybgctkwbu